export const SET_CREDENTIALS = 'SET_CREDENTIALS'
export const CLEAR_CREDENTIALS = 'CLEAR_CREDENTIALS'

export const SET_TOAST_MSG = 'SET_TOAST_MSG'
export const DISPLAY_TOAST_MSG = 'DISPLAY_TOAST_MSG'

export const SET_SELECTED_CITY = 'SET_SELECTED_CITY'

export const NAVIGATE = 'NAVIGATE'