export const AUTO_LOGIN = 'AUTO_LOGIN'

export const AUTHENTICATE = 'AUTHENTICATE'
export const USER_LOADING = 'USER_LOADING'
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'

export const LOGOUT = 'LOGOUT'

export const CREATE_ADDRESS = 'CREATE_ADDRESS'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'

export const LOAD_ADDRESSES = 'LOAD_ADDRESSES'
export const LOAD_ADDRESSES_SUCCESS = 'LOAD_ADDRESSES_SUCCESS'

export const LOAD_ADDRESS_BY_ZIPCODE = 'LOAD_ADDRESS_BY_ZIPCODE'
export const LOAD_ADDRESS_BY_ZIPCODE_SUCCESS = 'LOAD_ADDRESS_BY_ZIPCODE_SUCCESS'