export const AUTO_LOGIN = 'AUTO_LOGIN'

export const AUTHENTICATE = 'AUTHENTICATE'
export const USER_LOADING = 'USER_LOADING'
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'

export const LOGOUT = 'LOGOUT'

export const CREATE_ADDRESS = 'CREATE_ADDRESS'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'

export const LOAD_ADDRESSES = 'LOAD_ADDRESSES'
export const LOAD_ADDRESSES_SUCCESS = 'LOAD_ADDRESSES_SUCCESS'

export const LOAD_ADDRESS_INFO = 'LOAD_ADDRESS_INFO'
export const LOAD_ADDRESS_INFO_SUCCESS = 'LOAD_ADDRESS_INFO_SUCCESS'

export const SELECTED_ADDRESS = 'SELECTED_ADDRESS'

export const LOAD_ORDERS = 'LOAD_ORDERS'
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS'

export const LOAD_ORDER = 'LOAD_ORDER'
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS'

export const SYNC_ORDER = 'SYNC_ORDER'
export const SYNC_ORDER_SUCCESS = 'SYNC_ORDER_SUCCESS'

export const SELECTED_ORDER = 'SELECTED_ORDER'