export const SELECT_STORE = 'SELECT_STORE'
export const ADD_TO_CART = 'ADD_TO_CART'

export const HANDLE_NEW_PRODUCT = 'HANDLE_NEW_PRODUCT'

export const PLACE_ORDER = 'PLACE_ORDER'
export const PLACE_ORDER_LOADING = 'PLACE_ORDER_LOADING'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'