export const SELECT_STORE = 'SELECT_STORE'
export const ADD_TO_CART = 'ADD_TO_CART'

export const HANDLE_NEW_PRODUCT = 'HANDLE_NEW_PRODUCT'

export const PLACE_ORDER = 'PLACE_ORDER'
export const PLACE_ORDER_LOADING = 'PLACE_ORDER_LOADING'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'

export const CLEAR_CART = 'CLEAR_CART'

export const SET_OPENED_ORDER = 'SET_OPENED_ORDER'

export const SYNC_ORDER = 'SYNC_ORDER'
export const HANDLE_SYNC_ORDER_SUCCESS = 'HANDLE_SYNC_ORDER_SUCCESS'
export const SYNC_ORDER_SUCCESS = 'SYNC_ORDER_SUCCESS'

export const SYNC_DRIVER = 'SYNC_DRIVER'
export const SYNC_DRIVER_SUCCESS = 'SYNC_DRIVER_SUCCESS'
