// @flow
export const STORES_LOADING = 'STORES_LOADING'
export const STORES_ERROR = 'STORES_ERROR'

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'

export const LOAD_STORE = 'LOAD_STORE'
export const LOAD_STORE_SUCCESS = 'LOAD_STORE_SUCCESS'
